apiVersion: v1
kind: Config
clusters:
- name: "local"
  cluster:
    server: "https://verbose-potato-7vx56prq7r5p2x4gj-443.app.github.dev/k8s/clusters/local"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2RENDQ\
      VdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNV\
      GMxTVRrdwpORGsxTWpBZUZ3MHlOVEEzTURjeE5qRTFOVEphRncwek5UQTNNRFV4TmpFMU5USmFNR\
      Vl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV\
      1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE56VXhPVEEwT1RVeU1Ga3dFd1lIS29aSXpqMENBU\
      VlJS29aSXpqMERBUWNEUWdBRXl3T21CREpVSFVDZwo1WE5pQks2R0drTWN0TURIT3RkckczenJqS\
      G0yM3dnWkYvRTB5NDQ3RlNEcldVbU9nM1hwMXpoMy8xZ0FQZEdtClNJWWtoMFdRL0tOQ01FQXdEZ\
      1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGR\
      HpVa0RUMTB3a2tFbE1XQnRvZmZGNlJYc2lITUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUMzTgpxc\
      EVJWElKWnROcEtxaXRVN0FrYVF0NUlDVnRxZDYzY1d2bzlUK1g2QWlCaktjYkF0c0VNSUJpY3EyM\
      1g2b2dnCnB2WjRyYTlUakI2RjNhYjRTRXR2d3c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"

users:
- name: "local"
  user:
    token: "kubeconfig-user-mzpdphtbp4:j6wplwrnvvq2jc8ngzlghnrmsbvsh8thdp8dslbcnnw4dfr2vkv7zr"


contexts:
- name: "local"
  context:
    user: "local"
    cluster: "local"

current-context: "local"
