apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://verbose-potato-7vx56prq7r5p2x4gj-443.app.github.dev/k8s/clusters/local
  name: local
contexts:
- context:
    cluster: local
    user: local
  name: local
current-context: local
kind: Config
preferences: {}
users:
- name: local
  user:
    token: kubeconfig-user-tgc26tdkgb:zrqdp4jvsfjcpr678d4rx76hjhjwk76bc7q54kt4j8svfnspg74bj5
